### ISSUE TITLE
希望能够获取一份RK3288官方套件的updat.img

### ISSUE THREAD

**Issue by sunxufu** [rockchip-linux/docker-rockchip#3]
目前所用板子为官方的RK3288 SDK开发板，为安卓系统，需要升级为ubuntu系统，因此希望能够获取相关升级update.img文件，邮箱：sun_xufu@163.com 谢谢！

**Comment by rkchrome** [comment]
你可以第三方软件找找，ubuntu的rootfs基本通用．由于商业版权缘故，Rockchip不提供此系统.
可以考虑使用debian替换ubuntu.

https://github.com/rockchip-linux/rk-rootfs-build

**Comment by sunxufu** [comment]
您好:
       感谢您的回复，按照您的建议，我下载了firefly的ubuntu固件并将其刷入了开发板中，不过遗憾的是似乎并未奏效，板子现在成黑屏状态。我将固件升级工具下的LOG文件贴于附件中，麻烦您指导一下。由于我并不是弄嵌入式开发的，所以对这一方面存在很多盲区，还望理解与海涵。


祝工作顺利!
绪福
Tel:17751114603






在2018年7月4日 09:03，rkchrome<notifications@github.com> 写道：

你可以第三方软件找找，ubuntu的rootfs基本通用．由于商业版权缘故，Rockchip不提供此系统.
可以考虑使用debian替换ubuntu.

https://github.com/rockchip-linux/rk-rootfs-build

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
﻿15:19:08 601	Android开发工具 v2.3.5.2 start run
15:21:44 776	Layer<1-3>:下载Boot开始
15:21:47 317	Layer<1-3>:下载Boot成功
15:21:47 321	Layer<1-3>:等待Maskrom开始
15:21:47 709	Layer<1-3>:等待Maskrom成功
15:21:47 712	Layer<1-3>:测试设备开始
15:21:47 714	Layer<1-3>:测试设备成功
15:21:47 716	Layer<1-3>:校验芯片开始
15:21:47 718	Layer<1-3>:校验芯片成功
15:21:47 721	Layer<1-3>:获取FlashInfo开始
15:21:47 722	<LAYER 1-3> INFO:FlashInfo: 00 00 E9 00 00 04 04 00 28 00 01
15:21:47 724	Layer<1-3>:获取FlashInfo成功
15:21:47 726	Layer<1-3>:准备IDB开始
15:21:47 727	<LAYER 1-3> INFO:CS(1)		(7456MB)		(SAMSUNG)
15:21:47 734	Layer<1-3>:准备IDB成功
15:21:47 736	Layer<1-3>:下载IDB开始
15:21:49 212	Layer<1-3>:下载IDB成功
15:21:49 214	Layer<1-3>:重启设备开始
15:21:50 218	Layer<1-3>:重启设备成功
15:21:50 221	Layer<1-3>:等待Loader开始
15:21:51 135	Layer<1-3>:等待Loader成功
15:21:51 138	Layer<1-3>:测试设备开始
15:21:51 141	Layer<1-3>:测试设备成功
15:21:51 143	Layer<1-3>:下载固件开始
15:21:51 144	<LAYER 1-3> INFO:Start download image,total=1268900912
15:21:51 180	<LAYER 1-3> INFO:Start to download misc,offset=0x12000,size=49152
15:21:51 187	<LAYER 1-3> INFO:Start to download resource,offset=0x2000,size=233472
15:21:51 204	<LAYER 1-3> INFO:Start to download boot,offset=0xa000,size=10321920
15:21:51 803	<LAYER 1-3> INFO:Start to download linuxroot,offset=0x2e000,size=1258291200
15:23:43 018	Layer<1-3>:下载固件成功
15:23:43 022	Layer<1-3>:重启设备开始
15:23:44 028	Layer<1-3>:重启设备成功

**Comment by Caesar-github** [comment]
The Obsolete issue.
If someone repro this issue again, please reopen the bug
