### ISSUE TITLE
docker build image issue

### ISSUE THREAD

**Issue by JimmyChung208** [rockchip-linux/docker-rockchip#4]
Hi
目前使用此docker使用sudo docker build -t rockchip .指令後
跑到最後會顯示
dpkg: error: cannot access archive '/packages/mpp/*.deb': No such file or directory
請問有缺少檔案嗎？
Thanks.

**Comment by Caesar-github** [comment]
Okay, the lastest code had fixed this issue,

**Comment by Caesar-github** [comment]
Please retest it again,  please reopen the bug if that's still exist issue
